/*
 * This file was automatically generated by SmartUnit
 */

package sut.com.wanxin.depository.common.intercept;

import org.junit.Test;
import static org.junit.Assert.*;
import java.lang.reflect.Method;
import static org.smartunit.shaded.org.mockito.Mockito.*;
import org.smartunit.shaded.org.mockito.ArgumentMatchers;
import com.wanxin.common.domain.BusinessException;
import com.wanxin.common.domain.ErrorCode;
import com.wanxin.common.domain.RestResponse;
import com.wanxin.depository.common.intercept.GlobalExceptionHandler;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.junit.runner.RunWith;
import org.smartunit.runtime.ExecutorServiceAnswer;
import org.smartunit.runtime.SmartRunner;
import org.smartunit.runtime.SmartRunnerParameters;
import org.smartunit.runtime.TransactionTemplateAnswer;
import org.smartunit.runtime.ViolatedAssumptionAnswer;
import org.springframework.lang.Nullable;

@RunWith(SmartRunner.class) @SmartRunnerParameters(mockJVMNonDeterminism = true, useVNET = true, resetStaticState = true) 
public class GlobalExceptionHandler_SSTest extends GlobalExceptionHandler_SSTest_scaffolding {
// allCoveredLines:[23, 26, 27, 28, 31, 34, 36, 38, 41, 42]

  @Test(timeout = 9000)
  public void test_exceptionGet_0()  throws Throwable  {
      //caseID:7e1c6ab33079b9f874bf92a98ad55514
      //CoveredLines: [23, 26, 27, 28, 31]
      //Input_0_HttpServletRequest: {}
      //Input_1_HttpServletResponse: {}
      //Input_2_Exception: errorCode0
      //Assert: assertEquals("\u81EA\u5B9A\u4E49\u5F02\u5E38", method_result.getMsg());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      //mock httpServletRequest0
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock httpServletResponse0
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock errorCode0
      ErrorCode errorCode0 = mock(ErrorCode.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      doReturn((-566)).when(errorCode0).getCode();
      doReturn("\u81EA\u5B9A\u4E49\u5F02\u5E38").when(errorCode0).getDesc();
      BusinessException businessException0 = new BusinessException(errorCode0);
      
      //Call method: exceptionGet
      RestResponse<Nullable> restResponse0 = globalExceptionHandler0.exceptionGet(httpServletRequest0, httpServletResponse0, businessException0);
      
      //Test Result Assert
      assertEquals("\u81EA\u5B9A\u4E49\u5F02\u5E38", restResponse0.getMsg());
  }

  @Test(timeout = 9000)
  public void test_exceptionGet_1()  throws Throwable  {
      //caseID:3ffa2d45b51b76053eb4bd0236f084d0
      //CoveredLines: [23, 26, 34, 36, 38, 41, 42]
      //Input_0_HttpServletRequest: {}
      //Input_1_HttpServletResponse: {}
      //Input_2_Exception: {}
      //Assert: assertEquals("\u672A\u77E5\u9519\u8BEF", method_result.getMsg());
      
      GlobalExceptionHandler globalExceptionHandler0 = new GlobalExceptionHandler();
      //mock httpServletRequest0
      HttpServletRequest httpServletRequest0 = mock(HttpServletRequest.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock httpServletResponse0
      HttpServletResponse httpServletResponse0 = mock(HttpServletResponse.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      //mock exception0
      Exception exception0 = mock(Exception.class, withSettings().defaultAnswer(new ViolatedAssumptionAnswer()).stubOnly());
      
      //Call method: exceptionGet
      RestResponse<Nullable> restResponse0 = globalExceptionHandler0.exceptionGet(httpServletRequest0, httpServletResponse0, exception0);
      
      //Test Result Assert
      assertEquals("\u672A\u77E5\u9519\u8BEF", restResponse0.getMsg());
  }
}
